version: "3.8"

services:
  database:
    image: postgres:16-alpine
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=unicorn_user
      - POSTGRES_PASSWORD=magical_password
      - POSTGRES_DB=calendso

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis-data:/data

  calcom:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://unicorn_user:magical_password@database/calendso
      - DATABASE_DIRECT_URL=postgresql://unicorn_user:magical_password@database/calendso
      - REDIS_URL=redis://redis:6379
    depends_on:
      - database
      - redis

volumes:
  database-data:
  redis-data:
